server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: pranavkrishnadanda # <--- CHANGE THIS TO YOUR ACTUAL PG USERNAME
    password:                    # <--- CHANGE THIS TO YOUR ACTUAL PG PASSWORD (if any, otherwise leave blank or remove)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging: # <--- ADD THIS BLOCK
  level:
    org.springframework.security: DEBUG